<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DemoConvocatoriasSeeder extends Seeder
{
    public function run(): void
    {
        // ─── Facultades ───────────────────────────────────────────────────────
        $facultades = [
            ['nombre_facultad' => 'Facultad de Ciencias Administrativas, Contables y Economicas', 'descripcion' => 'Administración, Contaduría y Economía'],
            ['nombre_facultad' => 'Facultad de Ciencias Ambientales y Desarrollo Sostenible',     'descripcion' => 'Ingeniería Ambiental y Sostenibilidad'],
            ['nombre_facultad' => 'Facultad de Derecho, Ciencias Sociales y Politicas',           'descripcion' => 'Derecho, Trabajo Social y Ciencias Políticas'],
            ['nombre_facultad' => 'Facultad de Educacion',                                        'descripcion' => 'Licenciaturas y Pedagogía'],
            ['nombre_facultad' => 'Facultad de Ingenieria',                                       'descripcion' => 'Ingeniería de Sistemas, Civil, Electrónica'],
        ];

        foreach ($facultades as $fac) {
            DB::table('facultades')->insertOrIgnore($fac);
        }

        $facIds = DB::table('facultades')->pluck('id_facultad', 'nombre_facultad');

        // ─── Tipo cargo IDs (inserted by TipoCargoSeeder) ─────────────────────
        $tipoCargoIds = DB::table('tipo_cargo')->pluck('id_tipo_cargo', 'nombre_tipo_cargo');

        // ─── Convocatorias ────────────────────────────────────────────────────
        $convocatorias = [
            [
                'nombre_convocatoria'         => 'Convocatoria Docente Ingeniería de Sistemas 2026-1',
                'numero_convocatoria'         => 'CD-2026-001',
                'tipo'                        => 'Cátedra',
                'periodo_academico'           => '2026-1',
                'tipo_cargo_id'               => $tipoCargoIds['Profesor Cátedra'] ?? null,
                'tipo_cargo_otro'             => null,
                'facultad_id'                 => $facIds['Facultad de Ingenieria'] ?? null,
                'facultad_otro'               => null,
                'cursos'                      => 'Programación Orientada a Objetos, Estructuras de Datos, Algoritmos y Programación',
                'tipo_vinculacion'            => 'Cátedra',
                'personas_requeridas'         => 3,
                'fecha_publicacion'           => '2026-01-10',
                'fecha_cierre'               => '2026-05-31',
                'fecha_inicio_contrato'       => '2026-02-03',
                'descripcion'                 => 'Se requieren docentes con experiencia en programación para dictar cursos en el programa de Ingeniería de Sistemas para el período académico 2026-1.',
                'estado_convocatoria'         => 'Abierta',
                'perfil_profesional_otro'     => 'Profesor Tiempo Parcial',
                'experiencia_requerida_id'    => null,
                'experiencia_requerida_fecha' => null,
                'solicitante'                 => 'Decanatura de Ingeniería',
                'tipo_experiencia_requerida'  => 'Docencia universitaria',
                'anos_experiencia_requerida'  => 2,
                'cantidad_experiencia'        => 2,
                'unidad_experiencia'          => 'Años',
                'referencia_experiencia'      => 'Experiencia docente en programación o desarrollo de software a nivel universitario',
                'requisitos_idiomas'          => json_encode([['idioma' => 'Inglés', 'nivel_minimo' => 'B1']]),
                'requisitos_adicionales'      => null,
                'avales_establecidos'         => null,
            ],
            [
                'nombre_convocatoria'         => 'Convocatoria Profesor Titular Economía 2026',
                'numero_convocatoria'         => 'CD-2026-002',
                'tipo'                        => 'Planta',
                'periodo_academico'           => '2026-1',
                'tipo_cargo_id'               => $tipoCargoIds['Profesor Titular'] ?? null,
                'tipo_cargo_otro'             => null,
                'facultad_id'                 => $facIds['Facultad de Ciencias Administrativas, Contables y Economicas'] ?? null,
                'facultad_otro'               => null,
                'cursos'                      => 'Microeconomía, Macroeconomía, Economía Internacional, Econometría',
                'tipo_vinculacion'            => 'Planta',
                'personas_requeridas'         => 1,
                'fecha_publicacion'           => '2026-01-15',
                'fecha_cierre'               => '2026-04-30',
                'fecha_inicio_contrato'       => '2026-06-01',
                'descripcion'                 => 'La Facultad de Ciencias Administrativas abre convocatoria para vincular un Profesor Titular en el área de Economía. Se requiere Doctorado y amplia experiencia investigativa y docente.',
                'estado_convocatoria'         => 'Abierta',
                'perfil_profesional_otro'     => 'Profesor Tiempo Completo',
                'experiencia_requerida_id'    => null,
                'experiencia_requerida_fecha' => '2021-01-01',
                'solicitante'                 => 'Decanatura de Ciencias Administrativas',
                'tipo_experiencia_requerida'  => 'Docencia universitaria',
                'anos_experiencia_requerida'  => 5,
                'cantidad_experiencia'        => 5,
                'unidad_experiencia'          => 'Años',
                'referencia_experiencia'      => 'Mínimo 5 años de docencia universitaria en áreas de Economía con producción académica demostrada',
                'requisitos_idiomas'          => json_encode([['idioma' => 'Inglés', 'nivel_minimo' => 'C1']]),
                'requisitos_adicionales'      => json_encode(['Doctorado en Economía o afines', 'Categoría Investigador Reconocido o superior en Minciencias']),
                'avales_establecidos'         => null,
            ],
            [
                'nombre_convocatoria'         => 'Convocatoria Docente Derecho Laboral 2026-1',
                'numero_convocatoria'         => 'CD-2026-003',
                'tipo'                        => 'Ocasional',
                'periodo_academico'           => '2026-1',
                'tipo_cargo_id'               => $tipoCargoIds['Profesor Asociado'] ?? null,
                'tipo_cargo_otro'             => null,
                'facultad_id'                 => $facIds['Facultad de Derecho, Ciencias Sociales y Politicas'] ?? null,
                'facultad_otro'               => null,
                'cursos'                      => 'Derecho Laboral, Derecho Constitucional, Derecho Administrativo',
                'tipo_vinculacion'            => 'Ocasional',
                'personas_requeridas'         => 2,
                'fecha_publicacion'           => '2026-02-01',
                'fecha_cierre'               => '2026-05-15',
                'fecha_inicio_contrato'       => '2026-02-17',
                'descripcion'                 => 'La Facultad de Derecho requiere docentes ocasionales para dictar asignaturas del área laboral y constitucional durante el período 2026-1.',
                'estado_convocatoria'         => 'Abierta',
                'perfil_profesional_otro'     => 'Especialista',
                'experiencia_requerida_id'    => null,
                'experiencia_requerida_fecha' => null,
                'solicitante'                 => 'Decanatura de Derecho',
                'tipo_experiencia_requerida'  => 'Docencia universitaria',
                'anos_experiencia_requerida'  => 3,
                'cantidad_experiencia'        => 3,
                'unidad_experiencia'          => 'Años',
                'referencia_experiencia'      => 'Experiencia docente en Derecho con énfasis en áreas laborales y constitucionales',
                'requisitos_idiomas'          => null,
                'requisitos_adicionales'      => json_encode(['Tarjeta profesional vigente de abogado', 'Maestría en Derecho o área afín']),
                'avales_establecidos'         => null,
            ],
            [
                'nombre_convocatoria'         => 'Convocatoria Investigador Ciencias Ambientales 2026',
                'numero_convocatoria'         => 'CD-2026-004',
                'tipo'                        => 'Planta',
                'periodo_academico'           => '2026-1',
                'tipo_cargo_id'               => $tipoCargoIds['Profesor Titular'] ?? null,
                'tipo_cargo_otro'             => null,
                'facultad_id'                 => $facIds['Facultad de Ciencias Ambientales y Desarrollo Sostenible'] ?? null,
                'facultad_otro'               => null,
                'cursos'                      => 'Gestión de Recursos Hídricos, Ecología, Impacto Ambiental, Legislación Ambiental',
                'tipo_vinculacion'            => 'Planta',
                'personas_requeridas'         => 1,
                'fecha_publicacion'           => '2025-12-01',
                'fecha_cierre'               => '2026-02-28',
                'fecha_inicio_contrato'       => '2026-03-15',
                'descripcion'                 => 'Convocatoria para investigador docente en el área de Ciencias Ambientales. Se requiere perfil investigativo con publicaciones en revistas indexadas y experiencia en gestión de proyectos de investigación.',
                'estado_convocatoria'         => 'Cerrada',
                'perfil_profesional_otro'     => 'Investigador',
                'experiencia_requerida_id'    => null,
                'experiencia_requerida_fecha' => '2020-01-01',
                'solicitante'                 => 'Decanatura de Ciencias Ambientales',
                'tipo_experiencia_requerida'  => 'Investigación',
                'anos_experiencia_requerida'  => 5,
                'cantidad_experiencia'        => 5,
                'unidad_experiencia'          => 'Años',
                'referencia_experiencia'      => 'Mínimo 5 años de experiencia en investigación ambiental con publicaciones en revistas Q1 o Q2',
                'requisitos_idiomas'          => json_encode([['idioma' => 'Inglés', 'nivel_minimo' => 'C1'], ['idioma' => 'Francés', 'nivel_minimo' => 'B1']]),
                'requisitos_adicionales'      => json_encode(['Doctorado en Ciencias Ambientales o afines', 'Mínimo 10 artículos publicados en revistas indexadas']),
                'avales_establecidos'         => null,
            ],
            [
                'nombre_convocatoria'         => 'Convocatoria Cátedra Licenciatura en Matemáticas 2025-2',
                'numero_convocatoria'         => 'CD-2025-009',
                'tipo'                        => 'Cátedra',
                'periodo_academico'           => '2025-2',
                'tipo_cargo_id'               => $tipoCargoIds['Profesor Cátedra'] ?? null,
                'tipo_cargo_otro'             => null,
                'facultad_id'                 => $facIds['Facultad de Educacion'] ?? null,
                'facultad_otro'               => null,
                'cursos'                      => 'Didáctica de las Matemáticas, Cálculo Integral, Álgebra Lineal, Estadística Educativa',
                'tipo_vinculacion'            => 'Cátedra',
                'personas_requeridas'         => 4,
                'fecha_publicacion'           => '2025-06-01',
                'fecha_cierre'               => '2025-07-31',
                'fecha_inicio_contrato'       => '2025-08-04',
                'descripcion'                 => 'La Facultad de Educación requiere docentes de cátedra para el programa de Licenciatura en Matemáticas durante el período 2025-2.',
                'estado_convocatoria'         => 'Finalizada',
                'perfil_profesional_otro'     => 'Profesor Tiempo Parcial',
                'experiencia_requerida_id'    => null,
                'experiencia_requerida_fecha' => null,
                'solicitante'                 => 'Coordinador Licenciatura Matemáticas',
                'tipo_experiencia_requerida'  => 'Docencia universitaria',
                'anos_experiencia_requerida'  => 1,
                'cantidad_experiencia'        => 1,
                'unidad_experiencia'          => 'Años',
                'referencia_experiencia'      => 'Al menos 1 año de experiencia docente en matemáticas a nivel de educación superior o media',
                'requisitos_idiomas'          => null,
                'requisitos_adicionales'      => null,
                'avales_establecidos'         => null,
            ],
            [
                'nombre_convocatoria'         => 'Convocatoria Instructor TIC SENA 2026-1',
                'numero_convocatoria'         => 'CD-2026-005',
                'tipo'                        => 'Ocasional',
                'periodo_academico'           => '2026-1',
                'tipo_cargo_id'               => $tipoCargoIds['Instructor'] ?? null,
                'tipo_cargo_otro'             => null,
                'facultad_id'                 => $facIds['Facultad de Ingenieria'] ?? null,
                'facultad_otro'               => null,
                'cursos'                      => 'Introducción a la Programación, Bases de Datos, Redes y Comunicaciones',
                'tipo_vinculacion'            => 'Ocasional',
                'personas_requeridas'         => 2,
                'fecha_publicacion'           => '2026-03-01',
                'fecha_cierre'               => '2026-05-30',
                'fecha_inicio_contrato'       => '2026-04-01',
                'descripcion'                 => 'Se convoca a profesionales en Tecnologías de la Información para desempeñarse como instructores ocasionales en cursos de formación tecnológica en la Facultad de Ingeniería.',
                'estado_convocatoria'         => 'Abierta',
                'perfil_profesional_otro'     => 'Analista de Sistemas',
                'experiencia_requerida_id'    => null,
                'experiencia_requerida_fecha' => null,
                'solicitante'                 => 'Coordinador de Programa de Ingeniería de Sistemas',
                'tipo_experiencia_requerida'  => 'Otra',
                'anos_experiencia_requerida'  => 2,
                'cantidad_experiencia'        => 2,
                'unidad_experiencia'          => 'Años',
                'referencia_experiencia'      => 'Experiencia en desarrollo de software o administración de sistemas con al menos 2 años certificables',
                'requisitos_idiomas'          => json_encode([['idioma' => 'Inglés', 'nivel_minimo' => 'B1']]),
                'requisitos_adicionales'      => json_encode(['Título profesional en Ingeniería de Sistemas, Electrónica o afines']),
                'avales_establecidos'         => null,
            ],
            [
                'nombre_convocatoria'         => 'Convocatoria Profesor Asistente Contabilidad 2026',
                'numero_convocatoria'         => 'CD-2026-006',
                'tipo'                        => 'Planta',
                'periodo_academico'           => '2026-1',
                'tipo_cargo_id'               => $tipoCargoIds['Profesor Asistente'] ?? null,
                'tipo_cargo_otro'             => null,
                'facultad_id'                 => $facIds['Facultad de Ciencias Administrativas, Contables y Economicas'] ?? null,
                'facultad_otro'               => null,
                'cursos'                      => 'Contabilidad Financiera, Contabilidad de Costos, Auditoría, Normas NIIF',
                'tipo_vinculacion'            => 'Planta',
                'personas_requeridas'         => 1,
                'fecha_publicacion'           => '2026-02-15',
                'fecha_cierre'               => '2026-04-15',
                'fecha_inicio_contrato'       => '2026-06-01',
                'descripcion'                 => 'Convocatoria para vinculación de Profesor Asistente en el Departamento de Contabilidad y Finanzas. Se requiere Maestría y experiencia en docencia universitaria y sector privado.',
                'estado_convocatoria'         => 'Abierta',
                'perfil_profesional_otro'     => 'Especialista',
                'experiencia_requerida_id'    => null,
                'experiencia_requerida_fecha' => '2022-01-01',
                'solicitante'                 => 'Jefe Departamento de Contabilidad',
                'tipo_experiencia_requerida'  => 'Docencia universitaria',
                'anos_experiencia_requerida'  => 3,
                'cantidad_experiencia'        => 3,
                'unidad_experiencia'          => 'Años',
                'referencia_experiencia'      => 'Mínimo 3 años de experiencia docente en Contabilidad o Finanzas a nivel universitario',
                'requisitos_idiomas'          => json_encode([['idioma' => 'Inglés', 'nivel_minimo' => 'B2']]),
                'requisitos_adicionales'      => json_encode(['Maestría en Contabilidad, Finanzas o área afín', 'Tarjeta profesional de Contador Público vigente']),
                'avales_establecidos'         => null,
            ],
            [
                'nombre_convocatoria'         => 'Convocatoria Diseño Gráfico y Multimedia 2025-2',
                'numero_convocatoria'         => 'CD-2025-010',
                'tipo'                        => 'Cátedra',
                'periodo_academico'           => '2025-2',
                'tipo_cargo_id'               => $tipoCargoIds['Profesor Cátedra'] ?? null,
                'tipo_cargo_otro'             => null,
                'facultad_id'                 => null,
                'facultad_otro'               => 'Facultad de Artes y Humanidades',
                'cursos'                      => 'Diseño Digital, Multimedia, Fotografía Profesional, Diseño UX/UI',
                'tipo_vinculacion'            => 'Cátedra',
                'personas_requeridas'         => 2,
                'fecha_publicacion'           => '2025-07-01',
                'fecha_cierre'               => '2025-07-25',
                'fecha_inicio_contrato'       => '2025-08-04',
                'descripcion'                 => 'Se buscan docentes de cátedra para el programa de Diseño Gráfico y Multimedia en el período 2025-2, con experiencia en diseño digital, producción audiovisual o UX/UI.',
                'estado_convocatoria'         => 'Finalizada',
                'perfil_profesional_otro'     => 'Diseñador Instruccional',
                'experiencia_requerida_id'    => null,
                'experiencia_requerida_fecha' => null,
                'solicitante'                 => 'Coordinador Programa de Diseño',
                'tipo_experiencia_requerida'  => 'Profesoral',
                'anos_experiencia_requerida'  => 2,
                'cantidad_experiencia'        => 2,
                'unidad_experiencia'          => 'Años',
                'referencia_experiencia'      => 'Experiencia comprobable en diseño gráfico, diseño UX/UI o producción multimedia',
                'requisitos_idiomas'          => null,
                'requisitos_adicionales'      => json_encode(['Portafolio de proyectos de diseño requerido']),
                'avales_establecidos'         => null,
            ],
        ];

        foreach ($convocatorias as $conv) {
            $exists = DB::table('convocatorias')
                ->where('nombre_convocatoria', $conv['nombre_convocatoria'])
                ->exists();

            if (!$exists) {
                DB::table('convocatorias')->insert(array_merge(
                    $conv,
                    ['created_at' => now(), 'updated_at' => now()]
                ));
                echo "Convocatoria creada: {$conv['nombre_convocatoria']}\n";
            } else {
                echo "Convocatoria ya existe: {$conv['nombre_convocatoria']}\n";
            }
        }
    }
}
