<?php

namespace Database\Seeders;

use App\Models\Usuario\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DemoAspirantesSeeder extends Seeder
{
    public function run(): void
    {
        $aspirantes = [
            [
                'user' => [
                    'municipio_id'          => 703,
                    'tipo_identificacion'   => 'Cédula de ciudadanía',
                    'numero_identificacion' => '1012345678',
                    'genero'                => 'Femenino',
                    'primer_nombre'         => 'Laura',
                    'segundo_nombre'        => 'Valentina',
                    'primer_apellido'       => 'Gómez',
                    'segundo_apellido'      => 'Herrera',
                    'fecha_nacimiento'      => '1988-03-15',
                    'estado_civil'          => 'Casado',
                    'email'                 => 'laura.gomez@demo.com',
                    'password'              => Hash::make('demo1234'),
                ],
                'experiencias' => [
                    [
                        'tipo_experiencia'              => 'Docencia universitaria',
                        'institucion_experiencia'       => 'Universidad Nacional de Colombia',
                        'cargo'                         => 'Profesora de Cálculo',
                        'trabajo_actual'                => 'No',
                        'intensidad_horaria'            => 12,
                        'fecha_inicio'                  => '2015-01-15',
                        'fecha_finalizacion'            => '2020-06-30',
                        'fecha_expedicion_certificado'  => '2020-07-10',
                    ],
                    [
                        'tipo_experiencia'              => 'Investigación',
                        'institucion_experiencia'       => 'COLCIENCIAS',
                        'cargo'                         => 'Investigadora Junior',
                        'trabajo_actual'                => 'Si',
                        'intensidad_horaria'            => 40,
                        'fecha_inicio'                  => '2020-08-01',
                        'fecha_finalizacion'            => null,
                        'fecha_expedicion_certificado'  => null,
                    ],
                ],
                'idiomas' => [
                    [
                        'idioma'               => 'Inglés',
                        'institucion_idioma'   => 'British Council',
                        'fecha_certificado'    => '2017-05-20',
                        'nivel'                => 'C1',
                    ],
                    [
                        'idioma'               => 'Francés',
                        'institucion_idioma'   => 'Alliance Française',
                        'fecha_certificado'    => '2019-11-15',
                        'nivel'                => 'B2',
                    ],
                ],
                'estudios' => [
                    [
                        'tipo_estudio'           => 'Pregrado',
                        'graduado'               => 'Si',
                        'institucion'            => 'Universidad Nacional de Colombia',
                        'fecha_graduacion'       => '2011-06-30',
                        'titulo_convalidado'     => 'No',
                        'titulo_estudio'         => 'Matemáticas',
                        'fecha_inicio'           => '2006-02-01',
                        'fecha_fin'              => '2011-06-30',
                    ],
                    [
                        'tipo_estudio'           => 'Maestría',
                        'graduado'               => 'Si',
                        'institucion'            => 'Universidad de los Andes',
                        'fecha_graduacion'       => '2014-11-30',
                        'titulo_convalidado'     => 'No',
                        'titulo_estudio'         => 'Matemática Aplicada',
                        'fecha_inicio'           => '2012-02-01',
                        'fecha_fin'              => '2014-11-30',
                    ],
                ],
            ],
            [
                'user' => [
                    'municipio_id'          => 149,
                    'tipo_identificacion'   => 'Cédula de ciudadanía',
                    'numero_identificacion' => '1023456789',
                    'genero'                => 'Masculino',
                    'primer_nombre'         => 'Carlos',
                    'segundo_nombre'        => 'Andrés',
                    'primer_apellido'       => 'Martínez',
                    'segundo_apellido'      => 'López',
                    'fecha_nacimiento'      => '1982-07-22',
                    'estado_civil'          => 'Soltero',
                    'email'                 => 'carlos.martinez@demo.com',
                    'password'              => Hash::make('demo1234'),
                ],
                'experiencias' => [
                    [
                        'tipo_experiencia'              => 'Docencia universitaria',
                        'institucion_experiencia'       => 'Universidad de Antioquia',
                        'cargo'                         => 'Profesor de Programación',
                        'trabajo_actual'                => 'No',
                        'intensidad_horaria'            => 16,
                        'fecha_inicio'                  => '2010-02-01',
                        'fecha_finalizacion'            => '2018-12-31',
                        'fecha_expedicion_certificado'  => '2019-01-15',
                    ],
                    [
                        'tipo_experiencia'              => 'Otra',
                        'institucion_experiencia'       => 'Empresa TechColombia SAS',
                        'cargo'                         => 'Desarrollador Senior',
                        'trabajo_actual'                => 'Si',
                        'intensidad_horaria'            => 48,
                        'fecha_inicio'                  => '2019-01-15',
                        'fecha_finalizacion'            => null,
                        'fecha_expedicion_certificado'  => null,
                    ],
                    [
                        'tipo_experiencia'              => 'Investigación',
                        'institucion_experiencia'       => 'Universidad de Antioquia',
                        'cargo'                         => 'Asistente de Investigación',
                        'trabajo_actual'                => 'No',
                        'intensidad_horaria'            => 8,
                        'fecha_inicio'                  => '2012-03-01',
                        'fecha_finalizacion'            => '2016-12-31',
                        'fecha_expedicion_certificado'  => '2017-01-10',
                    ],
                ],
                'idiomas' => [
                    [
                        'idioma'               => 'Inglés',
                        'institucion_idioma'   => 'Centro Colombo Americano',
                        'fecha_certificado'    => '2015-08-10',
                        'nivel'                => 'B2',
                    ],
                ],
                'estudios' => [
                    [
                        'tipo_estudio'           => 'Pregrado',
                        'graduado'               => 'Si',
                        'institucion'            => 'Universidad de Antioquia',
                        'fecha_graduacion'       => '2007-11-30',
                        'titulo_convalidado'     => 'No',
                        'titulo_estudio'         => 'Ingeniería de Sistemas',
                        'fecha_inicio'           => '2002-02-01',
                        'fecha_fin'              => '2007-11-30',
                    ],
                    [
                        'tipo_estudio'           => 'Doctorado',
                        'graduado'               => 'Si',
                        'institucion'            => 'Universidad Politécnica de Madrid',
                        'fecha_graduacion'       => '2013-05-15',
                        'titulo_convalidado'     => 'Si',
                        'titulo_estudio'         => 'Doctorado en Ciencias de la Computación',
                        'fecha_inicio'           => '2009-09-01',
                        'fecha_fin'              => '2013-05-15',
                    ],
                ],
            ],
            [
                'user' => [
                    'municipio_id'          => 444,
                    'tipo_identificacion'   => 'Cédula de ciudadanía',
                    'numero_identificacion' => '1034567890',
                    'genero'                => 'Femenino',
                    'primer_nombre'         => 'María',
                    'segundo_nombre'        => 'Fernanda',
                    'primer_apellido'       => 'Rodríguez',
                    'segundo_apellido'      => 'Castro',
                    'fecha_nacimiento'      => '1990-11-05',
                    'estado_civil'          => 'Soltero',
                    'email'                 => 'maria.rodriguez@demo.com',
                    'password'              => Hash::make('demo1234'),
                ],
                'experiencias' => [
                    [
                        'tipo_experiencia'              => 'Docencia no universitaria',
                        'institucion_experiencia'       => 'Colegio San José de La Salle',
                        'cargo'                         => 'Profesora de Biología',
                        'trabajo_actual'                => 'No',
                        'intensidad_horaria'            => 22,
                        'fecha_inicio'                  => '2014-02-01',
                        'fecha_finalizacion'            => '2020-11-30',
                        'fecha_expedicion_certificado'  => '2020-12-10',
                    ],
                    [
                        'tipo_experiencia'              => 'Investigación',
                        'institucion_experiencia'       => 'Instituto de Investigaciones Biológicas',
                        'cargo'                         => 'Investigadora',
                        'trabajo_actual'                => 'Si',
                        'intensidad_horaria'            => 32,
                        'fecha_inicio'                  => '2021-01-15',
                        'fecha_finalizacion'            => null,
                        'fecha_expedicion_certificado'  => null,
                    ],
                ],
                'idiomas' => [
                    [
                        'idioma'               => 'Inglés',
                        'institucion_idioma'   => 'ICELT Cambridge',
                        'fecha_certificado'    => '2018-04-22',
                        'nivel'                => 'B1',
                    ],
                    [
                        'idioma'               => 'Portugués',
                        'institucion_idioma'   => 'Instituto Cultural Colombo Brasileño',
                        'fecha_certificado'    => '2020-09-10',
                        'nivel'                => 'A2',
                    ],
                ],
                'estudios' => [
                    [
                        'tipo_estudio'           => 'Pregrado',
                        'graduado'               => 'Si',
                        'institucion'            => 'Universidad del Valle',
                        'fecha_graduacion'       => '2014-05-30',
                        'titulo_convalidado'     => 'No',
                        'titulo_estudio'         => 'Biología',
                        'fecha_inicio'           => '2009-02-01',
                        'fecha_fin'              => '2014-05-30',
                    ],
                    [
                        'tipo_estudio'           => 'Especialización',
                        'graduado'               => 'Si',
                        'institucion'            => 'Universidad Javeriana',
                        'fecha_graduacion'       => '2016-06-30',
                        'titulo_convalidado'     => 'No',
                        'titulo_estudio'         => 'Especialización en Genética',
                        'fecha_inicio'           => '2015-02-01',
                        'fecha_fin'              => '2016-06-30',
                    ],
                    [
                        'tipo_estudio'           => 'Maestría',
                        'graduado'               => 'No',
                        'institucion'            => 'Universidad del Rosario',
                        'fecha_graduacion'       => null,
                        'titulo_convalidado'     => 'No',
                        'titulo_estudio'         => 'Maestría en Ciencias Biomédicas',
                        'fecha_inicio'           => '2022-02-01',
                        'fecha_fin'              => null,
                    ],
                ],
            ],
            [
                'user' => [
                    'municipio_id'          => 703,
                    'tipo_identificacion'   => 'Cédula de ciudadanía',
                    'numero_identificacion' => '1045678901',
                    'genero'                => 'Masculino',
                    'primer_nombre'         => 'Andrés',
                    'segundo_nombre'        => 'Felipe',
                    'primer_apellido'       => 'Torres',
                    'segundo_apellido'      => 'Vargas',
                    'fecha_nacimiento'      => '1978-04-18',
                    'estado_civil'          => 'Casado',
                    'email'                 => 'andres.torres@demo.com',
                    'password'              => Hash::make('demo1234'),
                ],
                'experiencias' => [
                    [
                        'tipo_experiencia'              => 'Docencia universitaria',
                        'institucion_experiencia'       => 'Universidad Autónoma de Colombia',
                        'cargo'                         => 'Profesor de Derecho Constitucional',
                        'trabajo_actual'                => 'Si',
                        'intensidad_horaria'            => 12,
                        'fecha_inicio'                  => '2005-08-01',
                        'fecha_finalizacion'            => null,
                        'fecha_expedicion_certificado'  => null,
                    ],
                    [
                        'tipo_experiencia'              => 'Dirección académica',
                        'institucion_experiencia'       => 'Universidad Autónoma de Colombia',
                        'cargo'                         => 'Coordinador de Posgrados en Derecho',
                        'trabajo_actual'                => 'No',
                        'intensidad_horaria'            => 40,
                        'fecha_inicio'                  => '2010-02-01',
                        'fecha_finalizacion'            => '2015-01-31',
                        'fecha_expedicion_certificado'  => '2015-02-10',
                    ],
                    [
                        'tipo_experiencia'              => 'Otra',
                        'institucion_experiencia'       => 'Firma de Abogados García & Torres',
                        'cargo'                         => 'Abogado Litigante',
                        'trabajo_actual'                => 'No',
                        'intensidad_horaria'            => 48,
                        'fecha_inicio'                  => '2002-06-01',
                        'fecha_finalizacion'            => '2005-07-31',
                        'fecha_expedicion_certificado'  => '2005-08-05',
                    ],
                ],
                'idiomas' => [
                    [
                        'idioma'               => 'Inglés',
                        'institucion_idioma'   => 'Centro Colombo Americano',
                        'fecha_certificado'    => '2010-03-15',
                        'nivel'                => 'B1',
                    ],
                    [
                        'idioma'               => 'Español',
                        'institucion_idioma'   => 'Universidad Autónoma de Colombia',
                        'fecha_certificado'    => '2001-12-01',
                        'nivel'                => 'C2',
                    ],
                ],
                'estudios' => [
                    [
                        'tipo_estudio'           => 'Pregrado',
                        'graduado'               => 'Si',
                        'institucion'            => 'Universidad Externado de Colombia',
                        'fecha_graduacion'       => '2002-05-15',
                        'titulo_convalidado'     => 'No',
                        'titulo_estudio'         => 'Derecho',
                        'fecha_inicio'           => '1997-02-01',
                        'fecha_fin'              => '2002-05-15',
                    ],
                    [
                        'tipo_estudio'           => 'Maestría',
                        'graduado'               => 'Si',
                        'institucion'            => 'Universidad de Salamanca',
                        'fecha_graduacion'       => '2008-09-30',
                        'titulo_convalidado'     => 'Si',
                        'titulo_estudio'         => 'Maestría en Derecho Constitucional',
                        'fecha_inicio'           => '2006-09-01',
                        'fecha_fin'              => '2008-09-30',
                    ],
                    [
                        'tipo_estudio'           => 'Doctorado',
                        'graduado'               => 'Si',
                        'institucion'            => 'Universidad Complutense de Madrid',
                        'fecha_graduacion'       => '2015-06-20',
                        'titulo_convalidado'     => 'Si',
                        'titulo_estudio'         => 'Doctorado en Derecho',
                        'fecha_inicio'           => '2010-09-01',
                        'fecha_fin'              => '2015-06-20',
                    ],
                ],
            ],
            [
                'user' => [
                    'municipio_id'          => 149,
                    'tipo_identificacion'   => 'Cédula de ciudadanía',
                    'numero_identificacion' => '1056789012',
                    'genero'                => 'Femenino',
                    'primer_nombre'         => 'Sofía',
                    'segundo_nombre'        => 'Alejandra',
                    'primer_apellido'       => 'Pérez',
                    'segundo_apellido'      => 'Mendoza',
                    'fecha_nacimiento'      => '1993-09-28',
                    'estado_civil'          => 'Soltero',
                    'email'                 => 'sofia.perez@demo.com',
                    'password'              => Hash::make('demo1234'),
                ],
                'experiencias' => [
                    [
                        'tipo_experiencia'              => 'Profesoral',
                        'institucion_experiencia'       => 'SENA Regional Bogotá',
                        'cargo'                         => 'Instructora de Diseño Gráfico',
                        'trabajo_actual'                => 'No',
                        'intensidad_horaria'            => 28,
                        'fecha_inicio'                  => '2017-03-01',
                        'fecha_finalizacion'            => '2022-02-28',
                        'fecha_expedicion_certificado'  => '2022-03-05',
                    ],
                    [
                        'tipo_experiencia'              => 'Docencia universitaria',
                        'institucion_experiencia'       => 'Universidad Jorge Tadeo Lozano',
                        'cargo'                         => 'Profesora de Diseño Digital',
                        'trabajo_actual'                => 'Si',
                        'intensidad_horaria'            => 16,
                        'fecha_inicio'                  => '2022-08-01',
                        'fecha_finalizacion'            => null,
                        'fecha_expedicion_certificado'  => null,
                    ],
                ],
                'idiomas' => [
                    [
                        'idioma'               => 'Inglés',
                        'institucion_idioma'   => 'British Council',
                        'fecha_certificado'    => '2019-07-12',
                        'nivel'                => 'B2',
                    ],
                    [
                        'idioma'               => 'Italiano',
                        'institucion_idioma'   => 'Istituto Italiano di Cultura',
                        'fecha_certificado'    => '2021-10-20',
                        'nivel'                => 'A1',
                    ],
                ],
                'estudios' => [
                    [
                        'tipo_estudio'           => 'Pregrado',
                        'graduado'               => 'Si',
                        'institucion'            => 'Universidad Jorge Tadeo Lozano',
                        'fecha_graduacion'       => '2016-11-30',
                        'titulo_convalidado'     => 'No',
                        'titulo_estudio'         => 'Diseño Gráfico',
                        'fecha_inicio'           => '2011-02-01',
                        'fecha_fin'              => '2016-11-30',
                    ],
                    [
                        'tipo_estudio'           => 'Especialización',
                        'graduado'               => 'Si',
                        'institucion'            => 'Universidad Pontificia Bolivariana',
                        'fecha_graduacion'       => '2018-06-30',
                        'titulo_convalidado'     => 'No',
                        'titulo_estudio'         => 'Especialización en UX/UI Design',
                        'fecha_inicio'           => '2017-08-01',
                        'fecha_fin'              => '2018-06-30',
                    ],
                ],
            ],
            [
                'user' => [
                    'municipio_id'          => 444,
                    'tipo_identificacion'   => 'Cédula de ciudadanía',
                    'numero_identificacion' => '1067890123',
                    'genero'                => 'Masculino',
                    'primer_nombre'         => 'Jorge',
                    'segundo_nombre'        => 'Iván',
                    'primer_apellido'       => 'Sánchez',
                    'segundo_apellido'      => 'Ríos',
                    'fecha_nacimiento'      => '1975-12-10',
                    'estado_civil'          => 'Divorciado',
                    'email'                 => 'jorge.sanchez@demo.com',
                    'password'              => Hash::make('demo1234'),
                ],
                'experiencias' => [
                    [
                        'tipo_experiencia'              => 'Docencia universitaria',
                        'institucion_experiencia'       => 'Universidad Surcolombiana',
                        'cargo'                         => 'Profesor Titular de Economía',
                        'trabajo_actual'                => 'Si',
                        'intensidad_horaria'            => 16,
                        'fecha_inicio'                  => '2003-02-01',
                        'fecha_finalizacion'            => null,
                        'fecha_expedicion_certificado'  => null,
                    ],
                    [
                        'tipo_experiencia'              => 'Dirección académica',
                        'institucion_experiencia'       => 'Universidad Surcolombiana',
                        'cargo'                         => 'Decano de la Facultad de Economía y Administración',
                        'trabajo_actual'                => 'No',
                        'intensidad_horaria'            => 40,
                        'fecha_inicio'                  => '2015-04-01',
                        'fecha_finalizacion'            => '2022-03-31',
                        'fecha_expedicion_certificado'  => '2022-04-10',
                    ],
                ],
                'idiomas' => [
                    [
                        'idioma'               => 'Inglés',
                        'institucion_idioma'   => 'Toefl ETS',
                        'fecha_certificado'    => '2012-06-20',
                        'nivel'                => 'C1',
                    ],
                    [
                        'idioma'               => 'Francés',
                        'institucion_idioma'   => 'Alliance Française',
                        'fecha_certificado'    => '2014-11-08',
                        'nivel'                => 'B1',
                    ],
                    [
                        'idioma'               => 'Alemán',
                        'institucion_idioma'   => 'Instituto Goethe',
                        'fecha_certificado'    => '2018-03-22',
                        'nivel'                => 'A2',
                    ],
                ],
                'estudios' => [
                    [
                        'tipo_estudio'           => 'Pregrado',
                        'graduado'               => 'Si',
                        'institucion'            => 'Universidad Nacional de Colombia',
                        'fecha_graduacion'       => '1999-11-30',
                        'titulo_convalidado'     => 'No',
                        'titulo_estudio'         => 'Economía',
                        'fecha_inicio'           => '1994-02-01',
                        'fecha_fin'              => '1999-11-30',
                    ],
                    [
                        'tipo_estudio'           => 'Maestría',
                        'graduado'               => 'Si',
                        'institucion'            => 'Universidad de los Andes',
                        'fecha_graduacion'       => '2002-09-30',
                        'titulo_convalidado'     => 'No',
                        'titulo_estudio'         => 'Maestría en Economía',
                        'fecha_inicio'           => '2000-08-01',
                        'fecha_fin'              => '2002-09-30',
                    ],
                    [
                        'tipo_estudio'           => 'Doctorado',
                        'graduado'               => 'Si',
                        'institucion'            => 'Universidad de Barcelona',
                        'fecha_graduacion'       => '2009-07-15',
                        'titulo_convalidado'     => 'Si',
                        'titulo_estudio'         => 'Doctorado en Economía',
                        'fecha_inicio'           => '2004-09-01',
                        'fecha_fin'              => '2009-07-15',
                    ],
                ],
            ],
            [
                'user' => [
                    'municipio_id'          => 703,
                    'tipo_identificacion'   => 'Cédula de ciudadanía',
                    'numero_identificacion' => '1078901234',
                    'genero'                => 'Femenino',
                    'primer_nombre'         => 'Diana',
                    'segundo_nombre'        => 'Carolina',
                    'primer_apellido'       => 'Vargas',
                    'segundo_apellido'      => 'Morales',
                    'fecha_nacimiento'      => '1995-06-14',
                    'estado_civil'          => 'Soltero',
                    'email'                 => 'diana.vargas@demo.com',
                    'password'              => Hash::make('demo1234'),
                ],
                'experiencias' => [
                    [
                        'tipo_experiencia'              => 'Docencia no universitaria',
                        'institucion_experiencia'       => 'Colegio Campestre Los Pinos',
                        'cargo'                         => 'Profesora de Matemáticas e Informática',
                        'trabajo_actual'                => 'No',
                        'intensidad_horaria'            => 25,
                        'fecha_inicio'                  => '2019-02-01',
                        'fecha_finalizacion'            => '2023-11-30',
                        'fecha_expedicion_certificado'  => '2023-12-05',
                    ],
                    [
                        'tipo_experiencia'              => 'Profesoral',
                        'institucion_experiencia'       => 'SENA Regional Bogotá',
                        'cargo'                         => 'Instructora de Programación',
                        'trabajo_actual'                => 'Si',
                        'intensidad_horaria'            => 20,
                        'fecha_inicio'                  => '2024-01-15',
                        'fecha_finalizacion'            => null,
                        'fecha_expedicion_certificado'  => null,
                    ],
                ],
                'idiomas' => [
                    [
                        'idioma'               => 'Inglés',
                        'institucion_idioma'   => 'Centro Colombo Americano',
                        'fecha_certificado'    => '2021-03-18',
                        'nivel'                => 'B1',
                    ],
                ],
                'estudios' => [
                    [
                        'tipo_estudio'           => 'Pregrado',
                        'graduado'               => 'Si',
                        'institucion'            => 'Universidad Distrital Francisco José de Caldas',
                        'fecha_graduacion'       => '2018-11-30',
                        'titulo_convalidado'     => 'No',
                        'titulo_estudio'         => 'Licenciatura en Matemáticas',
                        'fecha_inicio'           => '2013-02-01',
                        'fecha_fin'              => '2018-11-30',
                    ],
                    [
                        'tipo_estudio'           => 'Especialización',
                        'graduado'               => 'No',
                        'institucion'            => 'Universidad Pedagógica Nacional',
                        'fecha_graduacion'       => null,
                        'titulo_convalidado'     => 'No',
                        'titulo_estudio'         => 'Especialización en Tecnología Educativa',
                        'fecha_inicio'           => '2024-02-01',
                        'fecha_fin'              => null,
                    ],
                ],
            ],
            [
                'user' => [
                    'municipio_id'          => 149,
                    'tipo_identificacion'   => 'Cédula de ciudadanía',
                    'numero_identificacion' => '1089012345',
                    'genero'                => 'Masculino',
                    'primer_nombre'         => 'Hernán',
                    'segundo_nombre'        => 'Darío',
                    'primer_apellido'       => 'Ospina',
                    'segundo_apellido'      => 'Cano',
                    'fecha_nacimiento'      => '1970-02-25',
                    'estado_civil'          => 'Casado',
                    'email'                 => 'hernan.ospina@demo.com',
                    'password'              => Hash::make('demo1234'),
                ],
                'experiencias' => [
                    [
                        'tipo_experiencia'              => 'Docencia universitaria',
                        'institucion_experiencia'       => 'Universidad de Córdoba',
                        'cargo'                         => 'Profesor de Ingeniería Ambiental',
                        'trabajo_actual'                => 'Si',
                        'intensidad_horaria'            => 20,
                        'fecha_inicio'                  => '1998-08-01',
                        'fecha_finalizacion'            => null,
                        'fecha_expedicion_certificado'  => null,
                    ],
                    [
                        'tipo_experiencia'              => 'Investigación',
                        'institucion_experiencia'       => 'Universidad de Córdoba',
                        'cargo'                         => 'Investigador Principal en Recursos Hídricos',
                        'trabajo_actual'                => 'Si',
                        'intensidad_horaria'            => 20,
                        'fecha_inicio'                  => '2005-01-15',
                        'fecha_finalizacion'            => null,
                        'fecha_expedicion_certificado'  => null,
                    ],
                    [
                        'tipo_experiencia'              => 'Otra',
                        'institucion_experiencia'       => 'Ministerio de Ambiente y Desarrollo Sostenible',
                        'cargo'                         => 'Consultor Ambiental',
                        'trabajo_actual'                => 'No',
                        'intensidad_horaria'            => 40,
                        'fecha_inicio'                  => '2010-03-01',
                        'fecha_finalizacion'            => '2013-02-28',
                        'fecha_expedicion_certificado'  => '2013-03-10',
                    ],
                ],
                'idiomas' => [
                    [
                        'idioma'               => 'Inglés',
                        'institucion_idioma'   => 'Toefl ETS',
                        'fecha_certificado'    => '2008-05-14',
                        'nivel'                => 'C2',
                    ],
                    [
                        'idioma'               => 'Francés',
                        'institucion_idioma'   => 'Alliance Française',
                        'fecha_certificado'    => '2011-09-22',
                        'nivel'                => 'C1',
                    ],
                ],
                'estudios' => [
                    [
                        'tipo_estudio'           => 'Pregrado',
                        'graduado'               => 'Si',
                        'institucion'            => 'Universidad Nacional de Colombia',
                        'fecha_graduacion'       => '1995-06-30',
                        'titulo_convalidado'     => 'No',
                        'titulo_estudio'         => 'Ingeniería Ambiental',
                        'fecha_inicio'           => '1990-02-01',
                        'fecha_fin'              => '1995-06-30',
                    ],
                    [
                        'tipo_estudio'           => 'Maestría',
                        'graduado'               => 'Si',
                        'institucion'            => 'Universidad Nacional Autónoma de México',
                        'fecha_graduacion'       => '1998-07-31',
                        'titulo_convalidado'     => 'Si',
                        'titulo_estudio'         => 'Maestría en Ciencias Ambientales',
                        'fecha_inicio'           => '1996-08-01',
                        'fecha_fin'              => '1998-07-31',
                    ],
                    [
                        'tipo_estudio'           => 'Doctorado',
                        'graduado'               => 'Si',
                        'institucion'            => 'Universidad Nacional de Colombia',
                        'fecha_graduacion'       => '2007-11-30',
                        'titulo_convalidado'     => 'No',
                        'titulo_estudio'         => 'Doctorado en Ciencias Ambientales',
                        'fecha_inicio'           => '2002-02-01',
                        'fecha_fin'              => '2007-11-30',
                    ],
                ],
            ],
            [
                'user' => [
                    'municipio_id'          => 444,
                    'tipo_identificacion'   => 'Cédula de ciudadanía',
                    'numero_identificacion' => '1090123456',
                    'genero'                => 'Femenino',
                    'primer_nombre'         => 'Valentina',
                    'segundo_nombre'        => 'Marcela',
                    'primer_apellido'       => 'Cruz',
                    'segundo_apellido'      => 'Suárez',
                    'fecha_nacimiento'      => '1986-08-30',
                    'estado_civil'          => 'Casado',
                    'email'                 => 'valentina.cruz@demo.com',
                    'password'              => Hash::make('demo1234'),
                ],
                'experiencias' => [
                    [
                        'tipo_experiencia'              => 'Docencia universitaria',
                        'institucion_experiencia'       => 'Universidad Autónoma de Bucaramanga',
                        'cargo'                         => 'Profesora de Contabilidad Financiera',
                        'trabajo_actual'                => 'No',
                        'intensidad_horaria'            => 12,
                        'fecha_inicio'                  => '2012-02-01',
                        'fecha_finalizacion'            => '2019-11-30',
                        'fecha_expedicion_certificado'  => '2019-12-05',
                    ],
                    [
                        'tipo_experiencia'              => 'Otra',
                        'institucion_experiencia'       => 'Deloitte Colombia',
                        'cargo'                         => 'Auditora Senior',
                        'trabajo_actual'                => 'Si',
                        'intensidad_horaria'            => 48,
                        'fecha_inicio'                  => '2020-01-15',
                        'fecha_finalizacion'            => null,
                        'fecha_expedicion_certificado'  => null,
                    ],
                ],
                'idiomas' => [
                    [
                        'idioma'               => 'Inglés',
                        'institucion_idioma'   => 'IELTS British Council',
                        'fecha_certificado'    => '2016-08-30',
                        'nivel'                => 'C1',
                    ],
                    [
                        'idioma'               => 'Chino Mandarín',
                        'institucion_idioma'   => 'Instituto Confucio',
                        'fecha_certificado'    => '2022-06-15',
                        'nivel'                => 'A1',
                    ],
                ],
                'estudios' => [
                    [
                        'tipo_estudio'           => 'Pregrado',
                        'graduado'               => 'Si',
                        'institucion'            => 'Universidad Industrial de Santander',
                        'fecha_graduacion'       => '2010-11-30',
                        'titulo_convalidado'     => 'No',
                        'titulo_estudio'         => 'Contaduría Pública',
                        'fecha_inicio'           => '2005-02-01',
                        'fecha_fin'              => '2010-11-30',
                    ],
                    [
                        'tipo_estudio'           => 'Maestría',
                        'graduado'               => 'Si',
                        'institucion'            => 'Universidad de los Andes',
                        'fecha_graduacion'       => '2013-06-30',
                        'titulo_convalidado'     => 'No',
                        'titulo_estudio'         => 'Maestría en Finanzas',
                        'fecha_inicio'           => '2011-08-01',
                        'fecha_fin'              => '2013-06-30',
                    ],
                ],
            ],
            [
                'user' => [
                    'municipio_id'          => 703,
                    'tipo_identificacion'   => 'Cédula de ciudadanía',
                    'numero_identificacion' => '1001234567',
                    'genero'                => 'Masculino',
                    'primer_nombre'         => 'Miguel',
                    'segundo_nombre'        => 'Ángel',
                    'primer_apellido'       => 'Restrepo',
                    'segundo_apellido'      => 'Aguirre',
                    'fecha_nacimiento'      => '1984-01-11',
                    'estado_civil'          => 'Viudo',
                    'email'                 => 'miguel.restrepo@demo.com',
                    'password'              => Hash::make('demo1234'),
                ],
                'experiencias' => [
                    [
                        'tipo_experiencia'              => 'Investigación',
                        'institucion_experiencia'       => 'Centro Internacional de Física',
                        'cargo'                         => 'Físico Investigador',
                        'trabajo_actual'                => 'No',
                        'intensidad_horaria'            => 48,
                        'fecha_inicio'                  => '2010-04-01',
                        'fecha_finalizacion'            => '2018-03-31',
                        'fecha_expedicion_certificado'  => '2018-04-15',
                    ],
                    [
                        'tipo_experiencia'              => 'Docencia universitaria',
                        'institucion_experiencia'       => 'Universidad de Caldas',
                        'cargo'                         => 'Profesor de Física Cuántica',
                        'trabajo_actual'                => 'Si',
                        'intensidad_horaria'            => 16,
                        'fecha_inicio'                  => '2018-08-01',
                        'fecha_finalizacion'            => null,
                        'fecha_expedicion_certificado'  => null,
                    ],
                ],
                'idiomas' => [
                    [
                        'idioma'               => 'Inglés',
                        'institucion_idioma'   => 'Cambridge University Press',
                        'fecha_certificado'    => '2014-11-05',
                        'nivel'                => 'C2',
                    ],
                    [
                        'idioma'               => 'Alemán',
                        'institucion_idioma'   => 'Instituto Goethe',
                        'fecha_certificado'    => '2016-04-18',
                        'nivel'                => 'B2',
                    ],
                    [
                        'idioma'               => 'Japonés',
                        'institucion_idioma'   => 'Japan Foundation',
                        'fecha_certificado'    => '2020-08-30',
                        'nivel'                => 'A1',
                    ],
                ],
                'estudios' => [
                    [
                        'tipo_estudio'           => 'Pregrado',
                        'graduado'               => 'Si',
                        'institucion'            => 'Universidad Nacional de Colombia',
                        'fecha_graduacion'       => '2007-11-30',
                        'titulo_convalidado'     => 'No',
                        'titulo_estudio'         => 'Física',
                        'fecha_inicio'           => '2002-02-01',
                        'fecha_fin'              => '2007-11-30',
                    ],
                    [
                        'tipo_estudio'           => 'Doctorado',
                        'graduado'               => 'Si',
                        'institucion'            => 'Massachusetts Institute of Technology',
                        'fecha_graduacion'       => '2013-05-30',
                        'titulo_convalidado'     => 'Si',
                        'titulo_estudio'         => 'Doctorado en Física',
                        'fecha_inicio'           => '2008-09-01',
                        'fecha_fin'              => '2013-05-30',
                    ],
                    [
                        'tipo_estudio'           => 'Postdoctorado',
                        'graduado'               => 'Si',
                        'institucion'            => 'CERN - Organización Europea para la Investigación Nuclear',
                        'fecha_graduacion'       => '2016-12-31',
                        'titulo_convalidado'     => 'Si',
                        'titulo_estudio'         => 'Postdoctorado en Física de Partículas',
                        'fecha_inicio'           => '2014-01-01',
                        'fecha_fin'              => '2016-12-31',
                    ],
                ],
            ],
        ];

        foreach ($aspirantes as $data) {
            $user = User::firstOrCreate(
                ['email' => $data['user']['email']],
                $data['user']
            );

            if ($user->wasRecentlyCreated) {
                $user->assignRole('Aspirante');
            }

            // Experiencias
            foreach ($data['experiencias'] as $exp) {
                DB::table('experiencias')->insertOrIgnore(array_merge(
                    ['user_id' => $user->id],
                    $exp,
                    ['created_at' => now(), 'updated_at' => now()]
                ));
            }

            // Idiomas
            foreach ($data['idiomas'] as $idioma) {
                DB::table('idiomas')->insertOrIgnore(array_merge(
                    ['user_id' => $user->id],
                    $idioma,
                    ['created_at' => now(), 'updated_at' => now()]
                ));
            }

            // Estudios
            foreach ($data['estudios'] as $estudio) {
                DB::table('estudios')->insertOrIgnore(array_merge(
                    ['user_id' => $user->id],
                    $estudio,
                    ['created_at' => now(), 'updated_at' => now()]
                ));
            }

            echo "Aspirante creado: {$user->primer_nombre} {$user->primer_apellido} ({$user->email})\n";
        }
    }
}
